name: mini_game_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.2.5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.0.20
  dropdown_button2: ^1.2.2
  flutter_typeahead: ^3.2.4
  system_tray: ^0.1.0
  flutter_window_close: ^0.2.1
  http: ^0.13.4
  floating_action_bubble: ^1.1.4
  font_awesome_flutter: ^10.0.0
  package_info_plus: ^1.4.0
  web_browser: ^0.5.0
  desktop_drop: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
