name: mini_game_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
